- hosts: localhost
  vars:
    - is_osx: ansible_os_family == 'Darwin'

  tasks:
    # essentials:
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/core.yml
    # - import_tasks: tasks/dotfiles.yml

    - import_tasks: tasks/atom.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/docker.yml

    # languages
    - import_tasks: tasks/python.yml

    # media
    - import_tasks: tasks/spotify.yml
