- hosts: localhost
  vars:
    - is_osx: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_distribution == 'Ubuntu'
    - is_ubuntu: ansible_distribution == 'Ubuntu'
    - is_ubuntu13_plus: is_ubuntu and ansible_distribution_version|int >= 13
    - is_ubuntu15_plus: is_ubuntu and ansible_distribution_version|int >= 15

  tasks:
    # essentials:
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/core.yml
    #- import_tasks: tasks/dotfiles.yml

    - import_tasks: tasks/atom.yml
    - import_tasks: tasks/code.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/docker.yml

    # languages:
    - import_tasks: tasks/racket.yml

