#!/bin/bash

if test ! $(which gcc); then
  echo "Installing xcode..."
  xcode-select --install
fi

if test ! "$(which brew)"; then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  brew update
fi

if test ! "$(which ansible)"; then
  echo "Installing ansible..."
  brew install ansible
else
  brew upgrade ansible
fi

python --version
ansible --version
ansible-playbook main.yml --ask-become-pass

test -d ~/.dotfiles && cd $_ && ./script/bootstrap
