- name: Install OSX-only core packages
  package: name={{ item }}
  with_items:
    - coreutils
    - findutils
    - gawk
    - gnu-getopt
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnutls
    - gpg
    - grc
    - pstree
    - unrar
    - watch
    - exa
    - diff-so-fancy

- name: Install core packages
  package: name={{ item }}
  with_items:
    - curl
    - git
    - htop
    - vim
    - wget
    - zsh
    - ncdu
    - tree

- name: Gets the zsh path
  shell: which zsh
  register: bin_zsh

- name: Add homebrew zsh to /etc/shells
  lineinfile: dest=/etc/shells line='{{ bin_zsh.stdout }}'
  become: True

- name: Install OSX-only apps
  homebrew_cask: name={{ item }}
  with_items:
    - day-o
