- name: Update Homebrew
  when: is_osx
  homebrew: update_homebrew=yes

- name: Add Homebrew taps
  when: is_osx
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions
